### ISSUE TITLE
TypeError: CleanWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by mitchallen** [nodes777/phaser3-react-template#74]
When trying to `npm run build`
```
node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

TypeError: CleanWebpackPlugin is not a constructor
```

**Comment by nodes777** [comment]
Thanks for this. Let me update all the dependencies and see if that resolves the issue.

**Comment by nodes777** [comment]
The issue is described on this [SO answer](https://stackoverflow.com/questions/56567930/typeerror-cleanwebpackplugin-is-not-a-constructor), just a quick update to the syntax. The [newest commit resolves this](https://github.com/nodes777/phaser3-react-template/commit/2d04d5be915a3301757a4f106718454f45d94ccf). Let me know if that works for you!

**Comment by mitchallen** [comment]
It works!
